- README.md
- config/services.yml
- src/Commands/Maintenance.php
fop:console:debug:mode : display maintenance status
fop:console:debug:mode enable : turn site off
fop:console:debug:mode disable : turn site on
fop:console:debug:mode toggle : change mode
fop:console:debug:mode status : display maintenance status
> Maintenance command

- fop_console.php
- src/Command.php
- src/Commands/CheckServiceContainer.php
- src/Commands/Debug/DebugMode.php
- src/Commands/Export.php
- src/Commands/LatestProducts.php
- src/Commands/Maintenance.php
- src/Commands/ShopStatus.php
- src/Context/ConsoleLoader.php
- src/Controllers/ConsoleController.php
Fix all php cs fixers errors in current module
> Apply Php Cs fixer with ps norms

- .gitignore
- README.md
- src/Commands/Maintenance.php
ids : list ip addresses
addip : add an ip
addmyip : try to add client ip address (ssh client address or local ip address)
Can b improved with check if ip address already in list. Remove fist , if list is empty
> add maintenance command to manage maintenance ip addresses

- src/Commands/Maintenance.php
> use of const ALLOWED_COMMAND

- fop_console.php
- src/Command.php
- src/Commands/CheckServiceContainer.php
- src/Commands/DebugMode.php
- src/Commands/Export.php
- src/Commands/LatestProducts.php
- src/Commands/Maintenance.php
- src/Commands/ShopStatus.php
- src/Context/ConsoleLoader.php
- src/Controllers/ConsoleController.php
> #4 Define Copyright header

- README.md
- src/Commands/CheckServiceContainer.php
- src/Commands/DebugMode.php
- src/Commands/Export.php
- src/Commands/LatestProducts.php
- src/Commands/Maintenance.php
- src/Commands/ShopStatus.php
rename commands to libname:category:action or just libname:category
issue : https://github.com/friends-of-presta/fop_console/issues/5
simplify shop-status to display all shops by default
> Simplify commands

- src/Commands/ShopStatus.php
php bin/console fop:shop-status 1 enable
> Ad a command to change shop status

- src/Commands/Images/GenerateAbstract.php
> Errors displayed.

- composer.json
Fix the fact that the module does not respect the composer requirement 
see : https://devdocs.prestashop.com/1.7/modules/concepts/composer/#important-notes
> Fix composer.json preprend-autoloader

- src/Commands/ClearCacheFiles.php
deleteOldCacheDirectory doesn't work. I need help. /S command line argument is always escaped.
> Clear cache : windows port

- README.md
Add checks about compatibility with Prestahop and php version in module README
( Fix wrong licence in readme too )
> Clarify module compatibility with Prestashop and php version

- .devtools/.phpstan_bootstrap.php
- .github/workflows/phpstan.yml
Alternative to #44 , without docker.
Pro : 
- It's way faster (event without caching download). 
- it's more robust (less external dependency (prestashop image on docker hub, docker commands))
Con : 
- we can't use "latest" as a tag/version.
- is not same as used by Prestashop corp.
> workflow phpstan without docker.

- config/services.yml
- src/Commands/ModuleHooks.php
Add new functionality from  issue #83 
New command bin/console fop:module:hooks _modulename_
> #83 Add a command to list registred hooks of a module

- README.md
> fix example command

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add github issue templates 
- bug report
- feature_request ( new command )
Fix #87 Improve issues for asking new command
Note that the merge need to be on the master branch
> Improve issues for asking new command

- .github/workflows/release_module.yml
> #101 : remove dev dependencies in release.

- .devtools/.phpstan_bootstrap.php
> rewrite .phpstan_bootstrap.php

- CONTRIBUTING.md
- README.md
> rewrite intro + links to ps devdocs & symfony.

- .devtools/phpstan_baseline.neon
- composer.json
- composer.lock
- phpstan.neon.dist
- src/Commands/MakeOverride.php
- src/Commands/ModuleHooks.php
- src/Context/ConsoleLoader.php
> Phpstan level5

- README.md
Explaining contribute process without mentioning fork led to confusion.
> Clarify contribution process

- .github/workflows/lint_yaml.yml
> lint yaml on github workflow

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
The issue template i have made for branch master were not backported to the dev branch :)
So we have the default issue templates again on the repository
> Backport #87 on branch dev

- README.md
- config/services.yml
- src/Commands/Employees/ListEmployees.php
Add a new command that list employees registered in the administration
> Add new command : List employees

- .devtools/.phpstan_bootstrap.php
grumphp first run : const FOP_PHPSTAN_PS_ROOT_CONFIG_FILE not replaced
> fix #147 - grumphp first run : const FOP_PHPSTAN_PS_ROOT_CONFIG_FILE not replaced

- config/services.yml
This is not currently a big deal but will fail with phpstan upcoming rule.
> remove \ in services yaml

- .devtools/phpstan/stubs/Product.stub
- phpstan.neon.dist
- src/Commands/Product/ProductLatest.php
> Fix #209 -  fop:product:latest crash if there's no new product in the shop

- src/Commands/Environment/EnvironmentSetupDev.php
J'ai modifié un fichier directement sur github, mais j'ai pas copié le bon fichier 😕 
ce PR fait la correction.
> Fix boulette

- src/Commands/Product/ProductLatest.php
> remove activated column (useless)

- src/Commands/Environment/EnvironmentDebug.php
> fop:environment:debug : note message when PS_DEV_MODE is set

- README.md
- config/services.yml
- src/Commands/Employee/EmployeeChangePassword.php
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Command name?      | fop:employees:change-password
| Command description?   | This command allow to change an employee password
| Command domain?  | Admin
| Command parameters?   | options : email ( Optional ) / password ( Optional )
I'll try to make a video to show the behaviors :)
> New Command Employee change password
